const GET_ACCOUNT_TRANSACTIONS = 'GET_ACCOUNT_TRANSACTIONS';
const GET_ACCOUNT_TRANSACTIONS_SUCCESS = 'GET_ACCOUNT_TRANSACTIONS_SUCCESS';
const GET_ACCOUNT_TRANSACTIONS_FAILED = 'GET_ACCOUNT_TRANSACTIONS_FAILED';

// NOTE: consider GET_ACCOUNT_BALANCE action

const CONVERT_CSV_DATA = 'CONVERT_CSV_DATA';
const CONVERT_CSV_DATA_SUCCESS = 'CONVERT_CSV_DATA_SUCCESS';
const CONVERT_CSV_DATA_FAILED = 'CONVERT_CSV_DATA_FAILED';

// NOTE: consider TRIM_TRANSACTIONS_BY_DATE action

const UPLOAD_NEW_TRANSACTIONS = 'UPLOAD_NEW_TRANSACTIONS';
const UPLOAD_NEW_TRANSACTIONS_SUCCESS = 'UPLOAD_NEW_TRANSACTIONS_SUCCESS';
const UPLOAD_NEW_TRANSACTIONS_FAILED = 'UPLOAD_NEW_TRANSACTIONS_FAILED';

export {
    GET_ACCOUNT_TRANSACTIONS,
    GET_ACCOUNT_TRANSACTIONS_SUCCESS,
    GET_ACCOUNT_TRANSACTIONS_FAILED,
    CONVERT_CSV_DATA,
    CONVERT_CSV_DATA_SUCCESS,
    CONVERT_CSV_DATA_FAILED,
    UPLOAD_NEW_TRANSACTIONS,
    UPLOAD_NEW_TRANSACTIONS_SUCCESS,
    UPLOAD_NEW_TRANSACTIONS_FAILED,
};
